# 开发环境配置文件

server:
  port: 8080

logging:
  level:
    com.xuelinr.database_mcp_server: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 数据库连接池配置
spring.datasource.hikari:
  maximum-pool-size: 10
  minimum-idle: 2
  connection-timeout: 20000

# 开发环境特定配置
app:
  environment: development
  debug: true

# 默认使用H2内存数据库方便开发测试
spring.datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: sa
  password: ""